# Site settings
title: Stefano Degenkamp
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Stefano Degenkamp
user_title: Junior Web Developer
email: stefanodegenkamp@gmail.com
twitter_username: lorem_ipsum
github_username:  Stefanode
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
